ploxiln/fab-classic

- .gitignore
- .travis.yml
- README.rst
small stuff, kind of testing pull requests
> README: minor tweaks, add test status badge

- .travis.yml
- dev-requirements.txt
- requirements.txt
- sites/www/installing.rst
and remove the separate requirements.txt, it's not needed
hopefully this makes tests 30 seconds faster
> remove documentation-build stuff from dev-requirements.txt

- .travis.yml
- dev-requirements.txt
- sites/docs/running_tests.rst
> minor dev-requirements and travis-config cleanups

- .travis.yml
- README.rst
and trimmed of commented-out stuff
> more explicit .travis.yml

- fabric/contrib/files.py
- sites/www/changelog.rst
> contrib: upload_template: more compatible shell syntax

- fabric/state.py
- sites/www/changelog.rst
> move getpass import inside try/except for win32 support

- fabric/sftp.py
> sftp put: clean up temp file for "sudo" mode on any error

- fabric/context_managers.py
- fabric/main.py
- fabric/operations.py
- fabric/utils.py
- setup.cfg
- tests/fake_filesystem.py
- tests/test_operations.py
- tests/utils.py
not pythonic - use def, or a comprehension, or a loop
> respect flake8 rule: E731 do not assign a lambda expression

- fabric/network.py
- sites/docs/usage/execution.rst
only support a simple single hop
> support ProxyJump in the ssh config to use for gateway

- dev-requirements.txt
- fabric/version.py
also update some dev/release requirements
> bump to version 1.17.1a1 for development

- fabric/main.py
- fabric/tasks.py
- sites/docs/usage/fabfiles.rst
- tests/test_main.py
minor modernization of `__import__`
minor disentangling of parallel wrapper inner function
> cleanup fabfile import and parallel wrapper

- fabric/network.py
- tests/test_network.py
- tests/utils.py
instead of just showing password prompt
fixes ploxiln/fab-classic#21
> network: print unrecognized SSHException as string

- .github/workflows/linux.yml
- README.rst
- sites/docs/conf.py
travis-ci references, testing website/docs build
> finish switch to github-actions

- .github/workflows/linux.yml
- MANIFEST.in
- fabric/version.py
- tests/test_network.py
requires updating some tests expected output
> tests: add paramiko-ng 2.8.0 to CI test matrix

- fabric/network.py
for easier copy/paste
port of https://github.com/fabric/fabric/pull/1099
> network: space around hostname in disconnect message

- .github/workflows/linux.yml
- fabric/operations.py
- fabric/version.py
> release v1.19.0

- fabric/operations.py
- tests/test_operations.py
accidentally broken in https://github.com/ploxiln/fab-classic/pull/54
closes https://github.com/ploxiln/fab-classic/issues/58
> fix local() handling of failing commands with capture=False

- .github/workflows/linux.yml
- dev-requirements.txt
yeah yeah should switch to pytest plain mock someday ...
> tests: keep old nose and fudge working with setuptools<58

- tests/test_tasks.py
> tests: delete unused helper dict_contains()

- .github/workflows/linux.yml
including "upstream" / original fork of paramiko
> ci: add new paramiko versions
